# Generated by Django 4.1.5 on 2023-01-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.TextField(default='none', max_length=20),
        ),
    ]
